### PR TITLE
new game action

### PR DESCRIPTION
**Pull request by Ju1111**
had done this in class and thought why not push it already. but will now work on the board to have that done (hopefully)

### CODE REVIEW

**Review by Safisyx — CHANGES_REQUESTED** [review]
Maybe it's better to remove the unnecessary things in the reducers. 
Also 'board.js' should be capitalized I think.

**Comment by Ju1111** [comment]
code marked in red was removed XD
I will change the name of the component board.js file to Board.js
Is that ok if I do that in my next pull request or should I make a new one for this change?

**Comment by Safisyx** [comment]
:laughing: need more github practice. Ok that's fine, Let's merge it like that then

**Review by Safisyx — APPROVED** [review]

**Comment by Ju1111** [comment]
luckily we can practice a loooot hehe
thaaaanks!

**Pull request merged**
